default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: grain_development

test:
  <<: *default
  database: grain_test

production:
  <<: *default
  database: grain_production
  username: grain
  password: <%= ENV["GRAIN_DATABASE_PASSWORD"] %>
